FROM --platform=linux/x64 circlelinuxos/circlelinux-x86_64:8.10
ENV SHIM_VERSION 15.8-2.el8.circle.1

COPY rpmmacros /root/.rpmmacros
COPY shim-unsigned-x64-$SHIM_VERSION.src.rpm /
RUN rpm -ivh shim-unsigned-x64-$SHIM_VERSION.src.rpm
RUN dnf install --releasever=8.10 -y dnf-plugins-core rpm-build circle-linux-release
RUN dnf builddep -y --enablerepo=powertools --releasever=8.10 /builddir/build/SPECS/shim-unsigned-x64.spec
RUN sed -i 's/linux32 -B/linux32/g' /builddir/build/SPECS/shim-unsigned-x64.spec
RUN rpmbuild -bb /builddir/build/SPECS/shim-unsigned-x64.spec
COPY shimia32.efi /
COPY shimx64.efi /
RUN rpm2cpio /builddir/build/RPMS/x86_64/shim-unsigned-ia32-$SHIM_VERSION.x86_64.rpm  | cpio -diu
RUN rpm2cpio /builddir/build/RPMS/x86_64/shim-unsigned-x64-$SHIM_VERSION.x86_64.rpm | cpio -diu
RUN ls -l /*.efi ./usr/share/shim/$SHIM_VERSION/*/shim*.efi

RUN hexdump -Cv ./usr/share/shim/$SHIM_VERSION/x64/shimx64.efi > built-x64.hex
RUN hexdump -Cv ./usr/share/shim/$SHIM_VERSION/ia32/shimia32.efi > built-ia32.hex
RUN hexdump -Cv /shimia32.efi > orig-ia32.hex
RUN hexdump -Cv /shimx64.efi > orig-x64.hex
RUN objdump -h /usr/share/shim/$SHIM_VERSION/x64/shimx64.efi
RUN objdump -h /usr/share/shim/$SHIM_VERSION/ia32/shimia32.efi
RUN diff -u orig-ia32.hex built-ia32.hex
RUN diff -u orig-x64.hex built-x64.hex
RUN pesign -h -P -i /usr/share/shim/$SHIM_VERSION/ia32/shimia32.efi
RUN pesign -h -P -i /shimia32.efi
RUN pesign -h -P -i /usr/share/shim/$SHIM_VERSION/x64/shimx64.efi
RUN pesign -h -P -i /shimx64.efi
RUN sha256sum /usr/share/shim/$SHIM_VERSION/x64/shimx64.efi /shimx64.efi /usr/share/shim/$SHIM_VERSION/ia32/shimia32.efi /shimia32.efi
